export const INIT_BILL_REQUEST = 'INIT_BILL_REQUEST';
export const INIT_BILL_SUCCESS = 'INIT_BILL_SUCCESS';
export const INIT_BILL_FAIL = 'INIT_BILL_FAIL';
export const INIT_BILL_RESET = 'INIT_BILL_RESET';

export const GET_BILL_DETAILS_REQUEST = 'GET_BILL_DETAILS_REQUEST';
export const GET_BILL_DETAILS_SUCCESS = 'GET_BILL_DETAILS_SUCCESS';
export const GET_BILL_DETAILS_FAIL = 'GET_BILL_DETAILS_FAIL';
export const GET_BILL_DETAILS_RESET = 'GET_BILL_DETAILS_RESET';

export const GET_BILL_PRODUCTS_REQUEST = 'GET_BILL_PRODUCTS_REQUEST';
export const GET_BILL_PRODUCTS_SUCCESS = 'GET_BILL_PRODUCTS_SUCCESS';
export const GET_BILL_PRODUCTS_FAIL = 'GET_BILL_PRODUCTS_FAIL';
export const GET_BILL_PRODUCTS_RESET = 'GET_BILL_PRODUCTS_RESET';

export const REMOVE_PRODUCT_FROM_BILL_REQUEST =
  'REMOVE_PRODUCT_FROM_BILL_REQUEST';
export const REMOVE_PRODUCT_FROM_BILL_SUCCESS =
  'REMOVE_PRODUCT_FROM_BILL_SUCCESS';
export const REMOVE_PRODUCT_FROM_BILL_FAIL = 'REMOVE_PRODUCT_FROM_BILL_FAIL';
export const REMOVE_PRODUCT_FROM_BILL_RESET = 'REMOVE_PRODUCT_FROM_BILL_RESET';

export const RESTORE_PRODUCT_TO_BILL_REQUEST =
  'RESTORE_PRODUCT_TO_BILL_REQUEST';
export const RESTORE_PRODUCT_TO_BILL_SUCCESS =
  'RESTORE_PRODUCT_TO_BILL_SUCCESS';
export const RESTORE_PRODUCT_TO_BILL_FAIL = 'RESTORE_PRODUCT_TO_BILL_FAIL';
export const RESTORE_PRODUCT_TO_BILL_RESET = 'RESTORE_PRODUCT_TO_BILL_RESET';

export const CANCEL_BILL_REQUEST = 'CANCEL_BILL_REQUEST';
export const CANCEL_BILL_SUCCESS = 'CANCEL_BILL_SUCCESS';
export const CANCEL_BILL_FAIL = 'CANCEL_BILL_FAIL';
export const CANCEL_BILL_RESET = 'CANCEL_BILL_RESET';

export const RESTORE_BILL_REQUEST = 'RESTORE_BILL_REQUEST';
export const RESTORE_BILL_SUCCESS = 'RESTORE_BILL_SUCCESS';
export const RESTORE_BILL_FAIL = 'RESTORE_BILL_FAIL';
export const RESTORE_BILL_RESET = 'RESTORE_BILL_RESET';

export const ACCEPT_BILL_REQUEST = 'ACCEPT_BILL_REQUEST';
export const ACCEPT_BILL_SUCCESS = 'ACCEPT_BILL_SUCCESS';
export const ACCEPT_BILL_FAIL = 'ACCEPT_BILL_FAIL';
export const ACCEPT_BILL_RESET = 'ACCEPT_BILL_RESET';

export const SEND_BILL_REQUEST = 'SEND_BILL_REQUEST';
export const SEND_BILL_SUCCESS = 'SEND_BILL_SUCCESS';
export const SEND_BILL_FAIL = 'SEND_BILL_FAIL';
export const SEND_BILL_RESET = 'SEND_BILL_RESET';

export const BARCODE_REQUEST = 'BARCODE_REQUEST';
export const BARCODE_SUCCESS = 'BARCODE_SUCCESS';
export const BARCODE_FAIL = 'BARCODE_FAIL';
export const BARCODE_RESET = 'BARCODE_RESET';

export const UPDATE_BILL_PRODUCTS_REQUEST = 'UPDATE_BILL_PRODUCTS_REQUEST';
export const UPDATE_BILL_PRODUCTS_SUCCESS = 'UPDATE_BILL_PRODUCTS_SUCCESS';
export const UPDATE_BILL_PRODUCTS_FAIL = 'UPDATE_BILL_PRODUCTS_FAIL';
export const UPDATE_BILL_PRODUCTS_RESET = 'UPDATE_BILL_PRODUCTS_RESET';
