export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL'
export const GET_CITIES_RESET = 'GET_CITIES_RESET'

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY'
export const SET_CURRENT_CITY_RESET = 'SET_CURRENT_CITY_RESET'

export const ADD_CITY_REQUEST = 'ADD_CITY_REQUEST'
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS'
export const ADD_CITY_FAIL = 'ADD_CITY_FAIL'
export const ADD_CITY_RESET = 'ADD_CITY_RESET'

export const DELETE_CITY_REQUEST = 'DELETE_CITY_REQUEST'
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS'
export const DELETE_CITY_FAIL = 'DELETE_CITY_FAIL'
export const DELETE_CITY_RESET = 'DELETE_CITY_RESET'


export const UPDATE_CITY_REQUEST = 'UPDATE_CITY_REQUEST'
export const UPDATE_CITY_SUCCESS = 'UPDATE_CITY_SUCCESS'
export const UPDATE_CITY_FAIL = 'UPDATE_CITY_FAIL'
export const UPDATE_CITY_RESET = 'UPDATE_CITY_RESET'

export const HIDE_CITY_REQUEST = 'HIDE_CITY_REQUEST'
export const HIDE_CITY_SUCCESS = 'HIDE_CITY_SUCCESS'
export const HIDE_CITY_FAIL = 'HIDE_CITY_FAIL'

export const SHOW_CITY_REQUEST = 'SHOW_CITY_REQUEST'
export const SHOW_CITY_SUCCESS = 'SHOW_CITY_SUCCESS'
export const SHOW_CITY_FAIL = 'SHOW_CITY_FAIL'
