export const GET_CUSTOMERS_REQUEST = 'GET_CUSTOMERS_REQUEST'
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS'
export const GET_CUSTOMERS_FAIL = 'GET_CUSTOMERS_FAIL'
export const GET_CUSTOMERS_RESET = 'GET_CUSTOMERS_RESET'

export const SET_CURRENT_CUSTOMER = 'SET_CURRENT_CUSTOMER'
export const SET_CURRENT_CUSTOMER_RESET = 'SET_CURRENT_CUSTOMER_RESET'

export const ADD_CUSTOMER_REQUEST = 'ADD_CUSTOMER_REQUEST'
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS'
export const ADD_CUSTOMER_FAIL = 'ADD_CUSTOMER_FAIL'
export const ADD_CUSTOMER_RESET = 'ADD_CUSTOMER_RESET'

export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL'
export const DELETE_CUSTOMER_RESET = 'DELETE_CUSTOMER_RESET'


export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL'
export const UPDATE_CUSTOMER_RESET = 'UPDATE_CUSTOMER_RESET'

export const BLOCK_CUSTOMER_REQUEST = 'BLOCK_CUSTOMER_REQUEST'
export const BLOCK_CUSTOMER_SUCCESS = 'BLOCK_CUSTOMER_SUCCESS'
export const BLOCK_CUSTOMER_FAIL = 'BLOCK_CUSTOMER_FAIL'
export const BLOCK_CUSTOMER_RESET = 'BLOCK_CUSTOMER_RESET'

export const UNBLOCK_CUSTOMER_REQUEST = 'UNBLOCK_CUSTOMER_REQUEST'
export const UNBLOCK_CUSTOMER_SUCCESS = 'UNBLOCK_CUSTOMER_SUCCESS'
export const UNBLOCK_CUSTOMER_FAIL = 'UNBLOCK_CUSTOMER_FAIL'
export const UNBLOCK_CUSTOMER_RESET = 'UNBLOCK_CUSTOMER_RESET'
