export const GET_DELIVERY_COMPANIES_REQUEST = 'GET_DELIVERY_COMPANIES_REQUEST'
export const GET_DELIVERY_COMPANIES_SUCCESS = 'GET_DELIVERY_COMPANIES_SUCCESS'
export const GET_DELIVERY_COMPANIES_FAIL = 'GET_DELIVERY_COMPANIES_FAIL'
export const GET_DELIVERY_COMPANIES_RESET = 'GET_DELIVERY_COMPANIES_RESET'

export const ADD_DELIVERY_COMPANY_REQUEST = 'ADD_DELIVERY_COMPANY_REQUEST'
export const ADD_DELIVERY_COMPANY_SUCCESS = 'ADD_DELIVERY_COMPANY_SUCCESS'
export const ADD_DELIVERY_COMPANY_FAIL = 'ADD_DELIVERY_COMPANY_FAIL'
export const ADD_DELIVERY_COMPANY_RESET = 'ADD_DELIVERY_COMPANY_RESET'

export const EDIT_DELIVERY_COMPANY_REQUEST = 'EDIT_DELIVERY_COMPANY_REQUEST'
export const EDIT_DELIVERY_COMPANY_SUCCESS = 'EDIT_DELIVERY_COMPANY_SUCCESS'
export const EDIT_DELIVERY_COMPANY_FAIL = 'EDIT_DELIVERY_COMPANY_FAIL'
export const EDIT_DELIVERY_COMPANY_RESET = 'EDIT_DELIVERY_COMPANY_RESET'

export const DELETE_DELIVERY_COMPANY_REQUEST = 'DELETE_DELIVERY_COMPANY_REQUEST'
export const DELETE_DELIVERY_COMPANY_SUCCESS = 'DELETE_DELIVERY_COMPANY_SUCCESS'
export const DELETE_DELIVERY_COMPANY_FAIL = 'DELETE_DELIVERY_COMPANY_FAIL'
export const DELETE_DELIVERY_COMPANY_RESET = 'DELETE_DELIVERY_COMPANY_RESET'