export const GET_DELIVERY_COMPANIES_REQUEST = 'GET_DELIVERY_COMPANIES_REQUEST'
export const GET_DELIVERY_COMPANIES_SUCCESS = 'GET_DELIVERY_COMPANIES_SUCCESS'
export const GET_DELIVERY_COMPANIES_FAIL = 'GET_DELIVERY_COMPANIES_FAIL'
export const GET_DELIVERY_COMPANIES_RESET = 'GET_DELIVERY_COMPANIES_RESET'

export const SET_CURRENT_DELIVERY_COMPANY = 'SET_CURRENT_DELIVERY_COMPANY'
export const SET_CURRENT_DELIVERY_COMPANY_RESET = 'SET_CURRENT_DELIVERY_COMPANY_RESET'

export const ADD_DELIVERY_COMPANY_REQUEST = 'ADD_DELIVERY_COMPANY_REQUEST'
export const ADD_DELIVERY_COMPANY_SUCCESS = 'ADD_DELIVERY_COMPANY_SUCCESS'
export const ADD_DELIVERY_COMPANY_FAIL = 'ADD_DELIVERY_COMPANY_FAIL'
export const ADD_DELIVERY_COMPANY_RESET = 'ADD_DELIVERY_COMPANY_RESET'

export const DELETE_DELIVERY_COMPANY_REQUEST = 'DELETE_DELIVERY_COMPANY_REQUEST'
export const DELETE_DELIVERY_COMPANY_SUCCESS = 'DELETE_DELIVERY_COMPANY_SUCCESS'
export const DELETE_DELIVERY_COMPANY_FAIL = 'DELETE_DELIVERY_COMPANY_FAIL'
export const DELETE_DELIVERY_COMPANY_RESET = 'DELETE_DELIVERY_COMPANY_RESET'


export const UPDATE_DELIVERY_COMPANY_REQUEST = 'UPDATE_DELIVERY_COMPANY_REQUEST'
export const UPDATE_DELIVERY_COMPANY_SUCCESS = 'UPDATE_DELIVERY_COMPANY_SUCCESS'
export const UPDATE_DELIVERY_COMPANY_FAIL = 'UPDATE_DELIVERY_COMPANY_FAIL'
export const UPDATE_DELIVERY_COMPANY_RESET = 'UPDATE_DELIVERY_COMPANY_RESET'

export const HIDE_DELIVERY_COMPANY_REQUEST = 'HIDE_DELIVERY_COMPANY_REQUEST'
export const HIDE_DELIVERY_COMPANY_SUCCESS = 'HIDE_DELIVERY_COMPANY_SUCCESS'
export const HIDE_DELIVERY_COMPANY_FAIL = 'HIDE_DELIVERY_COMPANY_FAIL'

export const SHOW_DELIVERY_COMPANY_REQUEST = 'SHOW_DELIVERY_COMPANY_REQUEST'
export const SHOW_DELIVERY_COMPANY_SUCCESS = 'SHOW_DELIVERY_COMPANY_SUCCESS'
export const SHOW_DELIVERY_COMPANY_FAIL = 'SHOW_DELIVERY_COMPANY_FAIL'
