export const GET_EMPS_REQUEST = 'GET_EMPS_REQUEST';
export const GET_EMPS_SUCCESS = 'GET_EMPS_SUCCESS';
export const GET_EMPS_FAIL = 'GET_EMPS_FAIL';
export const GET_EMPS_RESET = 'GET_EMPS_RESET';

export const GET_EMPS_LIST_REQUEST = 'GET_EMPS_LIST_REQUEST';
export const GET_EMPS_LIST_SUCCESS = 'GET_EMPS_LIST_SUCCESS';
export const GET_EMPS_LIST_FAIL = 'GET_EMPS_LIST_FAIL';
export const GET_EMPS_LIST_RESET = 'GET_EMPS_LIST_RESET';

export const GET_EMPS_ORDER_STATS_REQUEST = 'GET_EMPS_ORDER_STATS_REQUEST';
export const GET_EMPS_ORDER_STATS_SUCCESS = 'GET_EMPS_ORDER_STATS_SUCCESS';
export const GET_EMPS_ORDER_STATS_FAIL = 'GET_EMPS_ORDER_STATS_FAIL';
export const GET_EMPS_ORDER_STATS_RESET = 'GET_EMPS_ORDER_STATS_RESET';

export const GET_EMPS_ONE_STATS_REQUEST = 'GET_EMPS_ONE_STATS_REQUEST';
export const GET_EMPS_ONE_STATS_SUCCESS = 'GET_EMPS_ONE_STATS_SUCCESS';
export const GET_EMPS_ONE_STATS_FAIL = 'GET_EMPS_ONE_STATS_FAIL';
export const GET_EMPS_ONE_STATS_RESET = 'GET_EMPS_ONE_STATS_RESET';

export const GET_EMPS_COMM_STATS_REQUEST = 'GET_EMPS_COMM_STATS_REQUEST';
export const GET_EMPS_COMM_STATS_SUCCESS = 'GET_EMPS_COMM_STATS_SUCCESS';
export const GET_EMPS_COMM_STATS_FAIL = 'GET_EMPS_COMM_STATS_FAIL';
export const GET_EMPS_COMM_STATS_RESET = 'GET_EMPS_COMM_STATS_RESET';

export const GET_EMPS_PAID_STATS_REQUEST = 'GET_EMPS_PAID_STATS_REQUEST';
export const GET_EMPS_PAID_STATS_SUCCESS = 'GET_EMPS_PAID_STATS_SUCCESS';
export const GET_EMPS_PAID_STATS_FAIL = 'GET_EMPS_PAID_STATS_FAIL';
export const GET_EMPS_PAID_STATS_RESET = 'GET_EMPS_PAID_STATS_RESET';

export const SET_CURRENT_EMP = 'SET_CURRENT_EMP';
export const SET_CURRENT_EMP_RESET = 'SET_CURRENT_EMP_RESET';

export const ADD_EMP_REQUEST = 'ADD_EMP_REQUEST';
export const ADD_EMP_SUCCESS = 'ADD_EMP_SUCCESS';
export const ADD_EMP_FAIL = 'ADD_EMP_FAIL';
export const ADD_EMP_RESET = 'ADD_EMP_RESET';

export const DELETE_EMP_REQUEST = 'DELETE_EMP_REQUEST';
export const DELETE_EMP_SUCCESS = 'DELETE_EMP_SUCCESS';
export const DELETE_EMP_FAIL = 'DELETE_EMP_FAIL';
export const DELETE_EMP_RESET = 'DELETE_EMP_RESET';

export const UPDATE_EMP_REQUEST = 'UPDATE_EMP_REQUEST';
export const UPDATE_EMP_SUCCESS = 'UPDATE_EMP_SUCCESS';
export const UPDATE_EMP_FAIL = 'UPDATE_EMP_FAIL';
export const UPDATE_EMP_RESET = 'UPDATE_EMP_RESET';

export const HIDE_EMP_REQUEST = 'HIDE_EMP_REQUEST';
export const HIDE_EMP_SUCCESS = 'HIDE_EMP_SUCCESS';
export const HIDE_EMP_FAIL = 'HIDE_EMP_FAIL';

export const SHOW_EMP_REQUEST = 'SHOW_EMP_REQUEST';
export const SHOW_EMP_SUCCESS = 'SHOW_EMP_SUCCESS';
export const SHOW_EMP_FAIL = 'SHOW_EMP_FAIL';

export const BLOCK_EMP_REQUEST = 'BLOCK_EMP_REQUEST';
export const BLOCK_EMP_SUCCESS = 'BLOCK_EMP_SUCCESS';
export const BLOCK_EMP_FAIL = 'BLOCK_EMP_FAIL';
export const BLOCK_EMP_RESET = 'BLOCK_EMP_RESET';

export const UNBLOCK_EMP_REQUEST = 'UNBLOCK_EMP_REQUEST';
export const UNBLOCK_EMP_SUCCESS = 'UNBLOCK_EMP_SUCCESS';
export const UNBLOCK_EMP_FAIL = 'UNBLOCK_EMP_FAIL';
export const UNBLOCK_EMP_RESET = 'UNBLOCK_EMP_RESET';

export const GET_REPORT_LIST_REQUEST = 'GET_REPORT_LIST_REQUEST';
export const GET_REPORT_LIST_SUCCESS = 'GET_REPORT_LIST_SUCCESS';
export const GET_REPORT_LIST_FAIL = 'GET_REPORT_LIST_FAIL';
export const GET_REPORT_LIST_RESET = 'GET_REPORT_LIST_RESET';

export const GET_REPORT_TABLE_REQUEST = 'GET_REPORT_TABLE_REQUEST';
export const GET_REPORT_TABLE_SUCCESS = 'GET_REPORT_TABLE_SUCCESS';
export const GET_REPORT_TABLE_FAIL = 'GET_REPORT_TABLE_FAIL';
export const GET_REPORT_TABLE_RESET = 'GET_REPORT_TABLE_RESET';

export const DELETE_REPORT_TABLE_REQUEST = 'DELETE_REPORT_TABLE_REQUEST';
export const DELETE_REPORT_TABLE_SUCCESS = 'DELETE_REPORT_TABLE_SUCCESS';
export const DELETE_REPORT_TABLE_FAIL = 'DELETE_REPORT_TABLE_FAIL';
export const DELETE_REPORT_TABLE_RESET = 'DELETE_REPORT_TABLE_RESET';

export const ADD_REPORT_TABLE_REQUEST = 'ADD_REPORT_TABLE_REQUEST';
export const ADD_REPORT_TABLE_SUCCESS = 'ADD_REPORT_TABLE_SUCCESS';
export const ADD_REPORT_TABLE_FAIL = 'ADD_REPORT_TABLE_FAIL';
export const ADD_REPORT_TABLE_RESET = 'ADD_REPORT_TABLE_RESET';

export const UPDATE_REPORT_TABLE_REQUEST = 'UPDATE_REPORT_TABLE_REQUEST';
export const UPDATE_REPORT_TABLE_SUCCESS = 'UPDATE_REPORT_TABLE_SUCCESS';
export const UPDATE_REPORT_TABLE_FAIL = 'UPDATE_REPORT_TABLE_FAIL';
export const UPDATE_REPORT_TABLE_RESET = 'UPDATE_REPORT_TABLE_RESET';
