export const GET_EMPS_REQUEST = 'GET_EMPS_REQUEST'
export const GET_EMPS_SUCCESS = 'GET_EMPS_SUCCESS'
export const GET_EMPS_FAIL = 'GET_EMPS_FAIL'
export const GET_EMPS_RESET = 'GET_EMPS_RESET'

export const SET_CURRENT_EMP = 'SET_CURRENT_EMP'
export const SET_CURRENT_EMP_RESET = 'SET_CURRENT_EMP_RESET'

export const ADD_EMP_REQUEST = 'ADD_EMP_REQUEST'
export const ADD_EMP_SUCCESS = 'ADD_EMP_SUCCESS'
export const ADD_EMP_FAIL = 'ADD_EMP_FAIL'
export const ADD_EMP_RESET = 'ADD_EMP_RESET'

export const DELETE_EMP_REQUEST = 'DELETE_EMP_REQUEST'
export const DELETE_EMP_SUCCESS = 'DELETE_EMP_SUCCESS'
export const DELETE_EMP_FAIL = 'DELETE_EMP_FAIL'
export const DELETE_EMP_RESET = 'DELETE_EMP_RESET'


export const UPDATE_EMP_REQUEST = 'UPDATE_EMP_REQUEST'
export const UPDATE_EMP_SUCCESS = 'UPDATE_EMP_SUCCESS'
export const UPDATE_EMP_FAIL = 'UPDATE_EMP_FAIL'
export const UPDATE_EMP_RESET = 'UPDATE_EMP_RESET'

export const HIDE_EMP_REQUEST = 'HIDE_EMP_REQUEST'
export const HIDE_EMP_SUCCESS = 'HIDE_EMP_SUCCESS'
export const HIDE_EMP_FAIL = 'HIDE_EMP_FAIL'

export const SHOW_EMP_REQUEST = 'SHOW_EMP_REQUEST'
export const SHOW_EMP_SUCCESS = 'SHOW_EMP_SUCCESS'
export const SHOW_EMP_FAIL = 'SHOW_EMP_FAIL'
