export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL'
export const GET_ORDERS_RESET = 'GET_ORDERS_RESET'


// export const SET_CURRENT_POST = 'SET_CURRENT_POST'
// export const SET_CURRENT_POST_RESET = 'SET_CURRENT_POST_RESET'

// export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
// export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
// export const ADD_POST_FAIL = 'ADD_POST_FAIL'
// export const ADD_POST_RESET = 'ADD_POST_RESET'

// export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
// export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
// export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'
// export const EDIT_POST_RESET = 'EDIT_POST_RESET'


// export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
// export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
// export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
// export const DELETE_POST_RESET = 'DELETE_POST_RESET'