export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
export const GET_PRODUCTS_RESET = 'GET_PRODUCTS_RESET';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_PRODUCT_RESET = 'GET_PRODUCT_RESET';

export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
export const SET_CURRENT_PRODUCT_RESET = 'SET_CURRENT_PRODUCT_RESET';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';
export const ADD_PRODUCT_RESET = 'ADD_PRODUCT_RESET';

export const ADD_PRODUCT_TO_ORDER_REQUEST = 'ADD_PRODUCT_TO_ORDER_REQUEST';
export const ADD_PRODUCT_TO_ORDER_SUCCESS = 'ADD_PRODUCT_TO_ORDER_SUCCESS';
export const ADD_PRODUCT_TO_ORDER_FAIL = 'ADD_PRODUCT_TO_ORDER_FAIL';
export const ADD_PRODUCT_TO_ORDER_RESET = 'ADD_PRODUCT_TO_ORDER_RESET';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';

export const HIDE_PRODUCT_REQUEST = 'HIDE_PRODUCT_REQUEST';
export const HIDE_PRODUCT_SUCCESS = 'HIDE_PRODUCT_SUCCESS';
export const HIDE_PRODUCT_FAIL = 'HIDE_PRODUCT_FAIL';

export const SHOW_PRODUCT_REQUEST = 'SHOW_PRODUCT_REQUEST';
export const SHOW_PRODUCT_SUCCESS = 'SHOW_PRODUCT_SUCCESS';
export const SHOW_PRODUCT_FAIL = 'SHOW_PRODUCT_FAIL';

export const SET_CURRENT_PRODUCTSIZE = 'SET_CURRENT_PRODUCTSIZE';
export const SET_CURRENT_PRODUCTSIZE_RESET = 'SET_CURRENT_PRODUCTSIZE_RESET';

export const CHECK_CART_FOR_PRODUCT_REQUEST = 'CHECK_CART_FOR_PRODUCT_REQUEST';
export const CHECK_CART_FOR_PRODUCT_SUCCESS = 'CHECK_CART_FOR_PRODUCT_SUCCESS';
export const CHECK_CART_FOR_PRODUCT_FAIL = 'CHECK_CART_FOR_PRODUCT_FAIL';
export const CHECK_CART_FOR_PRODUCT_RESET = 'CHECK_CART_FOR_PRODUCT_RESET';
