export const GET_SIZES_REQUEST = 'GET_SIZES_REQUEST'
export const GET_SIZES_SUCCESS = 'GET_SIZES_SUCCESS'
export const GET_SIZES_FAIL = 'GET_SIZES_FAIL'
export const GET_SIZES_RESET = 'GET_SIZES_RESET'

export const ADD_SIZE_REQUEST = 'ADD_SIZE_REQUEST'
export const ADD_SIZE_SUCCESS = 'ADD_SIZE_SUCCESS'
export const ADD_SIZE_FAIL = 'ADD_SIZE_FAIL'
export const ADD_SIZE_RESET = 'ADD_SIZE_RESET'

export const SET_CURRENT_SIZE = 'SET_CURRENT_SIZE'
export const SET_CURRENT_SIZE_RESET = 'SET_CURRENT_SIZE_RESET'

export const UPDATE_SIZE_REQUEST = 'UPDATE_SIZE_REQUEST'
export const UPDATE_SIZE_SUCCESS = 'UPDATE_SIZE_SUCCESS'
export const UPDATE_SIZE_FAIL = 'UPDATE_SIZE_FAIL'
export const UPDATE_SIZE_RESET = 'UPDATE_SIZE_RESET'


export const DELETE_SIZE_REQUEST = 'DELETE_SIZE_REQUEST'
export const DELETE_SIZE_SUCCESS = 'DELETE_SIZE_SUCCESS'
export const DELETE_SIZE_FAIL = 'DELETE_SIZE_FAIL'
export const DELETE_SIZE_RESET = 'DELETE_SIZE_RESET'

export const HIDE_SIZE_REQUEST = 'HIDE_SIZE_REQUEST'
export const HIDE_SIZE_SUCCESS = 'HIDE_SIZE_SUCCESS'
export const HIDE_SIZE_FAIL = 'HIDE_SIZE_FAIL'

export const SHOW_SIZE_REQUEST = 'SHOW_SIZE_REQUEST'
export const SHOW_SIZE_SUCCESS = 'SHOW_SIZE_SUCCESS'
export const SHOW_SIZE_FAIL = 'SHOW_SIZE_FAIL'