export const GET_SUBCATEGORIES_REQUEST = 'GET_SUBCATEGORIES_REQUEST';
export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS';
export const GET_SUBCATEGORIES_FAIL = 'GET_SUBCATEGORIES_FAIL';
export const GET_SUBCATEGORIES_RESET = 'GET_SUBCATEGORIES_RESET';


export const SET_CURRENT_SUBCATEGORY = 'SET_CURRENT_SUBCATEGORY'
export const SET_CURRENT_SUBCATEGORY_RESET = 'SET_CURRENT_SUBCATEGORY_RESET'
