export const GET_TARGETS_REQUEST = 'GET_TARGETS_REQUEST'
export const GET_TARGETS_SUCCESS = 'GET_TARGETS_SUCCESS'
export const GET_TARGETS_FAIL = 'GET_TARGETS_FAIL'
export const GET_TARGETS_RESET = 'GET_TARGETS_RESET'

export const ADD_TARGET_REQUEST = 'ADD_TARGET_REQUEST'
export const ADD_TARGET_SUCCESS = 'ADD_TARGET_SUCCESS'
export const ADD_TARGET_FAIL = 'ADD_TARGET_FAIL'
export const ADD_TARGET_RESET = 'ADD_TARGET_RESET'

export const SET_CURRENT_TARGET = 'SET_CURRENT_TARGET'
export const SET_CURRENT_TARGET_RESET = 'SET_CURRENT_TARGET_RESET'

export const UPDATE_TARGET_REQUEST = 'UPDATE_TARGET_REQUEST'
export const UPDATE_TARGET_SUCCESS = 'UPDATE_TARGET_SUCCESS'
export const UPDATE_TARGET_FAIL = 'UPDATE_TARGET_FAIL'
export const UPDATE_TARGET_RESET = 'UPDATE_TARGET_RESET'


export const DELETE_TARGET_REQUEST = 'DELETE_TARGET_REQUEST'
export const DELETE_TARGET_SUCCESS = 'DELETE_TARGET_SUCCESS'
export const DELETE_TARGET_FAIL = 'DELETE_TARGET_FAIL'
export const DELETE_TARGET_RESET = 'DELETE_TARGET_RESET'

export const HIDE_TARGET_REQUEST = 'HIDE_TARGET_REQUEST'
export const HIDE_TARGET_SUCCESS = 'HIDE_TARGET_SUCCESS'
export const HIDE_TARGET_FAIL = 'HIDE_TARGET_FAIL'

export const SHOW_TARGET_REQUEST = 'SHOW_TARGET_REQUEST'
export const SHOW_TARGET_SUCCESS = 'SHOW_TARGET_SUCCESS'
export const SHOW_TARGET_FAIL = 'SHOW_TARGET_FAIL'